# Pandas Complete Guide

Comprehensive guide to Pandas - the most important library for data manipulation and analysis in Python.

## Table of Contents

* [Introduction](#introduction)
* [Series and DataFrames](#series-and-dataframes)
* [DataFrame Basics and Inspection](#dataframe-basics-and-inspection)
* [Reading and Writing Data](#reading-and-writing-data)
* [Data Selection and Filtering](#data-selection-and-filtering)
* [Data Cleaning](#data-cleaning)
* [Sorting and Basic Statistics](#sorting-and-basic-statistics)
* [Grouping and Aggregation](#grouping-and-aggregation)
* [Merging and Joining](#merging-and-joining)
* [Time Series Operations](#time-series-operations)
* [Advanced Tricks and Performance](#advanced-tricks-and-performance)
* [Practice Exercises

## Introduction

### What is Pandas?

Pandas is a library for data manipulation and analysis. It provides:

* **DataFrame**: 2D labeled data structure (like Excel spreadsheet)
* **Series**: 1D labeled array
* **Powerful tools**: For cleaning, transforming, and analyzing data

### Why Pandas?

* **Easy data manipulation**: Load, clean, transform data easily
* **Handles missing data**: Built-in functions for dealing with NaN
* **Time series**: Excellent support for time-based data
* **Integration**: Works seamlessly with NumPy, Matplotlib, Scikit-learn

### Installation

In [ ]:
# pip install pandas

import pandas as pd
import numpy as np
print('Pandas version: ', pd.__version__)
print('Numpy version: ', np.__version__)

Pandas version:  3.0.2
Numpy version:  2.4.4

## Series and DataFrames

### Series

A Series is a one-dimensional labeled array.

In [6]:
# Creating Series
s = pd.Series([1,2,3,4,5])
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [8]:
# With custom index
s = pd.Series([10, 20, 30], index=['a','b','c'])
print(s)

a    10
b    20
c    30
dtype: int64

In [9]:
# From dictionary
s = pd.Series({
    'Alice':25,
    'Bob':30,
    'Charlie':35
})
print(s)

Alice      25
Bob        30
Charlie    35
dtype: int64

DataFrame

A DataFrame is a 2D labeled data structure with columns of potentially different types.

In [10]:
# Creating DataFrame from dictionary
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Age': [25, 30, 35, 28],
    'City': ['New York', 'London', 'Tokyo', 'Paris'],
    'Salary': [50000, 60000, 70000, 55000]
}

df = pd.DataFrame(data)
print(df)

      Name  Age      City  Salary
0    Alice   25  New York   50000
1      Bob   30    London   60000
2  Charlie   35     Tokyo   70000
3    Diana   28     Paris   55000

In [12]:
# From list of lists
data = [['Alice', 25], ['Bob', 30], ['Charlie', 35]]
df = pd.DataFrame(data, columns=['Name','Age'])
print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [13]:
# From NumPy array
arr = np.array([[1,2,3], [4,5,6]])
df = pd.DataFrame(arr, columns=['A','B','C'])
print(df)

   A  B  C
0  1  2  3
1  4  5  6

### DataFrame Properties

In [28]:

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Age': [25, 30, 35, 28],
    'City': ['New York', 'London', 'Tokyo', 'Paris'],
    'Salary': [50000, 60000, 70000, 55000]
}
df = pd.DataFrame(data)
print(df)

# print(df.shape)        # Output: (4, 4) - (rows, columns)
# print('--'*30)
# print(df.size)         # Output: 16 - total elements
# print('--'*30)
# print(df.columns)      # Output: Index(['Name', 'Age', 'City', 'Salary'])
# print('--'*30)
# print(df.index)        # Output: RangeIndex(start=0, stop=4, step=1)
# print('--'*30)
# print(df.dtypes)       # Data types of each column
# print('--'*30)
# print(df.info())       # Summary information
# print('--'*30)
# print(df.describe())   # Statistical summary

      Name  Age      City  Salary
0    Alice   25  New York   50000
1      Bob   30    London   60000
2  Charlie   35     Tokyo   70000
3    Diana   28     Paris   55000

## DataFrame Basics and Inspection

### Inspecting Data

Quickly understand your dataset using inspection functions:

In [22]:
print(df.shape)  # Output: (4, 4) - (rows, columns)

(4, 4)

In [23]:
print(df.size) # Output: 16 - total elements

16

In [24]:
print(df.columns) # Output: Index(['Name', 'Age', 'City',

Index(['Name', 'Age', 'City', 'Salary'], dtype='str')

In [25]:
print(df.index) # Output: RangeIndex(start=0, stop=4, step=1)

RangeIndex(start=0, stop=4, step=1)

In [29]:
print(df.dtypes)  # Data types of each column

Name        str
Age       int64
City        str
Salary    int64
dtype: object

In [30]:
print(df.info()) # Summary information

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Age     4 non-null      int64
 2   City    4 non-null      str
 3   Salary  4 non-null      int64
dtypes: int64(2), str(2)
memory usage: 304.0 bytes
None

In [31]:
print(df.describe())  # Statistical summary

             Age        Salary
count   4.000000      4.000000
mean   29.500000  58750.000000
std     4.203173   8539.125638
min    25.000000  50000.000000
25%    27.250000  53750.000000
50%    29.000000  57500.000000
75%    31.250000  62500.000000
max    35.000000  70000.000000

### Index & Columns Overview

Explore DataFrame components:

In [45]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Age': [25, 30, 35, 28],
    'City': ['New York', 'London', 'Tokyo', 'Paris'],
    'Salary': [50000, 60000, 70000, 55000]
}
df = pd.DataFrame(data)
print(df)

      Name  Age      City  Salary
0    Alice   25  New York   50000
1      Bob   30    London   60000
2  Charlie   35     Tokyo   70000
3    Diana   28     Paris   55000

In [42]:
# view index

print(df.index)  # Output: RangeIndex(start=0, stop=4, step=1)

RangeIndex(start=0, stop=4, step=1)

In [43]:
print(df.index.tolist())  # [0, 1, 2, 3]

[0, 1, 2, 3]

In [44]:
# View columns
print(df.columns)  # Output: Index(['Name', 'Age', 'City', 'Salary'])

Index(['Name', 'Age', 'City', 'Salary'], dtype='str')

In [49]:
# columns in list
print(df.columns.tolist)

<bound method IndexOpsMixin.tolist of Index(['Name', 'Age', 'City', 'Salary'], dtype='str')>

In [53]:
# Underlying NumPy data
print(df.values)   # Returns NumPy array

[['Alice' 25 'New York' 50000]
 ['Bob' 30 'London' 60000]
 ['Charlie' 35 'Tokyo' 70000]
 ['Diana' 28 'Paris' 55000]]

In [56]:
# Check if index/columns are unique
print(df.index.is_unique)  # True
print(df.columns.is_unique) # True

True
True

### Renaming Columns

In [57]:
# Rename single column

df = df.rename(columns = {'Age':'Years'})
print(df.columns)  # ['Name', 'Years', 'City', 'Salary']

Index(['Name', 'Years', 'City', 'Salary'], dtype='str')

In [58]:
# Rename multiple columns

df = df.rename(columns={
    'Name':'Full Name',
    'City':'Location',
    'Salary':'Income'
})
print(df.columns)

Index(['Full Name', 'Years', 'Location', 'Income'], dtype='str')

In [60]:
# Rename using mapper function
df = df.rename(columns=str.lower)  # Convert to lowercase
print(df.columns)
df = df.rename(columns=str.upper)  # Convert to uppercase
print(df.columns)

Index(['full name', 'years', 'location', 'income'], dtype='str')
Index(['FULL NAME', 'YEARS', 'LOCATION', 'INCOME'], dtype='str')

In [61]:
df

  FULL NAME  YEARS  LOCATION  INCOME
0     Alice     25  New York   50000
1       Bob     30    London   60000
2   Charlie     35     Tokyo   70000
3     Diana     28     Paris   55000

In [63]:
# In-place renaming
df.rename(columns={'YEARS':'AGE'}, inplace=True)  # affect permanently
print(df.columns)

Index(['FULL NAME', 'AGE', 'LOCATION', 'INCOME'], dtype='str')

  FULL NAME  AGE  LOCATION  INCOME
0     Alice   25  New York   50000
1       Bob   30    London   60000
2   Charlie   35     Tokyo   70000
3     Diana   28     Paris   55000

In [65]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Age': [25, 30, 35, 28],
    'City': ['New York', 'London', 'Tokyo', 'Paris'],
    'Salary': [50000, 60000, 70000, 55000]
}
df = pd.DataFrame(data)
print(df)

      Name  Age      City  Salary
0    Alice   25  New York   50000
1      Bob   30    London   60000
2  Charlie   35     Tokyo   70000
3    Diana   28     Paris   55000

### Setting and Resetting Index

In [66]:
# Set a column as index
df_indexed = df.set_index('Name')
print(df_indexed)

         Age      City  Salary
Name
Alice     25  New York   50000
Bob       30    London   60000
Charlie   35     Tokyo   70000
Diana     28     Paris   55000

In [68]:
# Reset index (move index back to column)
df_reset = df_indexed.reset_index()
print(df_reset)

      Name  Age      City  Salary
0    Alice   25  New York   50000
1      Bob   30    London   60000
2  Charlie   35     Tokyo   70000
3    Diana   28     Paris   55000

In [70]:
# Reset index without keeping old index as column

df_reset = df_indexed.reset_index(drop=True)
print(df_reset)

   Age      City  Salary
0   25  New York   50000
1   30    London   60000
2   35     Tokyo   70000
3   28     Paris   55000

In [73]:
# Set multiple columns as index
print(df)
print('--'*30)

df_multi = df.set_index(['City', 'Name'])
print(df_multi)

      Name  Age      City  Salary
0    Alice   25  New York   50000
1      Bob   30    London   60000
2  Charlie   35     Tokyo   70000
3    Diana   28     Paris   55000
------------------------------------------------------------
                  Age  Salary
City     Name
New York Alice     25   50000
London   Bob       30   60000
Tokyo    Charlie   35   70000
Paris    Diana     28   55000

### Basic Attributes Recap
Quick reference for core attributes:

```python
# Structure
df.shape          # (rows, columns)
df.size           # Total elements
df.ndim           # Number of dimensions

# Components
df.columns        # Column names
df.index          # Row index
df.values         # NumPy array


# Data types
df.dtypes         # Data type per column
df.dtypes.value_counts()  # Count of each data type

# Memory usage
df.memory_usage()  # Memory usage per column
df.memory_usage(deep=True)  # Deep memory usage (includes objects)

## Reading and Writing Data
### Reading CSV Files

```python
# Read CSV
df = pd.read_csv('data.csv')

# with options
df = pd.read_csv('data.csv',
                 sep=',',                    # Separator
                 header=0,                   # Row to use as header
                 index_col=0,                # Column to use as index
                 na_values=['NA', 'N/A'],    # Values to treat as NaN
                 nrows=1000)                 # Read only first 1000 rows


# Read with specific columns
df = pd.read_csv('data.csv', usecols=['Name', 'Age', Salary])
print(df)

### Reading Other Formats

```python
# Excel
df = pd.read_escel(r'data.xlsx', sheet_name='Sheet1')

# JSON
df = pd.read_json(f'data.json')

# HTML tables
df = pd.read_html(f'https://example.com/table.html')[0]

# SQL
import sqlite3
conn = sqlite3.connect('database.db')
df = read_sql_query('SELECT * FROM table', conn)

### Writing Data

```python

# Write to CSV
df.to_csv('output.csv', index=False)

# Write to Excel
df.to_excel('output.xlsx', sheet_name='Data', index=False)

# Write to json
df.to_json('output.json', orient='records')

# Write to sql
df.to_sql('table_na,e',conn, if_exists='replace', index=False)

```

## Data Selection and Filtering
### Selecting Columns

In [84]:
df = pd.DataFrame(data)
df

      Name  Age      City  Salary
0    Alice   25  New York   50000
1      Bob   30    London   60000
2  Charlie   35     Tokyo   70000
3    Diana   28     Paris   55000

In [88]:
# Single column (returns Series)
ages = df['Age']
print(ages)

# Multiple columns (returns DataFrame)
subset = df[['Name', 'Age']]
print('\n',subset)

0    25
1    30
2    35
3    28
Name: Age, dtype: int64

       Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    Diana   28

### Selecting Rows

In [ ]:
# By index  - iloc[]
first_row = df.iloc[0] # First row
first_three = df.iloc[:3]  # First 3 rows
print(first_row)
print('--'*30)
print(first_three)

Name         Alice
Age             25
City      New York
Salary       50000
Name: 0, dtype: object
------------------------------------------------------------
      Name  Age      City  Salary
0    Alice   25  New York   50000
1      Bob   30    London   60000
2  Charlie   35     Tokyo   70000

In [ ]:
# By label - loc[]
row = df.loc[0]  # Row with index 0
print(row)

Name         Alice
Age             25
City      New York
Salary       50000
Name: 0, dtype: object

In [97]:
# First/last n rows
head = df.head(3)             # First 3 rows
tail = df.tail(3)             # Last 3 rows

print(head)
print('--'*30, tail)

      Name  Age      City  Salary
0    Alice   25  New York   50000
1      Bob   30    London   60000
2  Charlie   35     Tokyo   70000
------------------------------------------------------------       Name  Age    City  Salary
1      Bob   30  London   60000
2  Charlie   35   Tokyo   70000
3    Diana   28   Paris   55000

### Filtering

In [98]:
# Boolean indexing
young = df[df['Age']<30]
print(young)

    Name  Age      City  Salary
0  Alice   25  New York   50000
3  Diana   28     Paris   55000

In [99]:
# Multiple conditions
filtered = df[(df['Age']>25) & (df['Salary']>55000)]
print(filtered)

      Name  Age    City  Salary
1      Bob   30  London   60000
2  Charlie   35   Tokyo   70000

In [104]:
# Using query method
filtered = df.query('Age >25 and Salary >55000')
print(filtered)

      Name  Age    City  Salary
1      Bob   30  London   60000
2  Charlie   35   Tokyo   70000

In [108]:
# isin() method
cities = ['New York', 'London']
filtered = df[df['City'].isin(cities)]
print(filtered)

    Name  Age      City  Salary
0  Alice   25  New York   50000
1    Bob   30    London   60000

### iloc vs loc

In [118]:
# iloc: Integer position-based indexing
print(df.iloc[0, 1])  # Row 0, Column 1
print('--'*20)
print(df.iloc[:3, 1:3])   # Rows 0-2, Columns 1-2
print('--'*20)

# loc: Label-based indexing
print(df.loc[0, 'Age'])   # Row with index 0, column 'Age'
print('--'*20)
print(df.loc[:2, 'Name':'City'])   # Rows 0-2, columns Name to City

25
----------------------------------------
   Age      City
0   25  New York
1   30    London
2   35     Tokyo
----------------------------------------
25
----------------------------------------
      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Tokyo

## Data Cleaning

### Handling Missing Values

Detect missing entries and handle them appropriately:

**Check for missing values**
```python
print(df.isnull)   # Boolean DataFrame (True where NaN)
print(df.isna())   # Same as isnull()
print(df.isnull().sum())  # Count missing per column
print(df.isna().sum())    # same
print(df.isnull().any())  # True if any missing in column
print(df.isnull().any().any()) # True if any missing in entire Dataframe

# Drop missing values
df_clean = df.dropna()  # default axis=0. Drop rows with any NaN
df_clean = df.dropna(axis=1)  # Drop columns with any NaN
df_clean = df.dropna(subset=['Age'])  # Drop rows where Age is NaN
df_clean = df.dropna(how='all')  # Drop rows where ALL values are NaN

# Fill missing values
df_filled = df.fillna(0)  # Fill with constant (0)
df_filled = df.fillna({'Age':0, 'Salary':50000}) # Fill different columns with different values
df_filled = df.fillna(df.mean()) # Fill with mean (numeric columns only)
df_filled = df['Age'].fillna(df['Age'].mean()) # Fill specific column with its mean
df_filled = df.fillna(df.median()) # Fill with median
df_filled = df.fillna(df.mode().iloc[0])  # Fill with mode

df_ffill = df.fillna(method='ffill') # Forward fill (use previous value)
df_bfill = df.fillna(method='bfill') # Backward fill (use next value)
df_ffill_limit = df.fillna(method='ffill', limit=2) # Limit forward fill to 2 consecutive NaNs

# Interpolation
df_interp = df.interpolate() # Linear Interpolation

### Handling Duplicates

```python
# Check for duplicates
print(df.duplicated()) # Boolean Series
print(df.duplicated().sum())  # Count duplicates

# Drop duplicates
df_unique = df.drop_duplicates()# Drop all duplicates
df_unique = df.drop_duplicates(subset=['Name']) # Drop based on column