# Chapter 1
## Pandas Series

# 1. Pandas Series কি?

- Series হলো এক ধরনের এক-ডাইমেনশনাল (1D) লেবেলড ডেটা স্ট্রাকচার, যা মূলত একটা কলামের মতো।
- একে একটা লিস্টের মতো ভাবা যায়, কিন্তু বাড়তি সুবিধা হলো এর সাথে index (label) থাকে।
- DataFrame-এর প্রতিটি কলাম আসলে একেকটা Series।

![image-2.png](attachment:image-2.png)
![image-3.png](attachment:image-3.png)
![image.png](attachment:image.png)
![image-4.png](attachment:image-4.png)

In [2]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# Create Series

In [2]:
# empty Series

import pandas as pd

s = pd.Series()
print(s)

Series([], dtype: object)

# series from List

In [4]:
# create series from List

country = country = ['Bangladesh', 'India', 'Pakistan','Nepal','Srilanka']
pd.Series(country)

0    Bangladesh
1         India
2      Pakistan
3         Nepal
4      Srilanka
dtype: str

In [7]:
# Create series from Nump Array
arr = np.array([1,2,3,4,5,6])
pd.Series(arr)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [8]:
# Create Series from integers

num = [32, 45, 12, 57, 100]
pd.Series(num)

0     32
1     45
2     12
3     57
4    100
dtype: int64

In [9]:
# Create Series from regular expression
import re

marks = [14,35,76,36,86]
subjects = ['math','eng','science','politics','social']
pd.Series(marks, subjects)  # index=subjects

math        14
eng         35
science     76
politics    36
social      86
dtype: int64

In [10]:
# setting a name
marks = [14,35,76,36,86]
subjects = ['math','eng','science','politics','social']
pd.Series(marks, index=subjects, name='Mehedi Hasans\'s Marks')

math        14
eng         35
science     76
politics    36
social      86
Name: Mehedi Hasans's Marks, dtype: int64

# Custom Index দিয়ে Series

In [11]:
s = pd.Series([120, 20, 30, 40, 50], index=['a','b','c','d','e'])
print(s)

a    120
b     20
c     30
d     40
e     50
dtype: int64

In [15]:
# Modifying index in Series
v = np.array([1,2,3,4,5,6,7])
s = pd.Series(v)
print(s)
s.index = (['a','b','c','d','e','f','g'])
print(s)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64
a    1
b    2
c    3
d    4
e    5
f    6
g    7
dtype: int64

# Series from dictionary

In [16]:
marks = {
    'math' : 49,
    'english' : 89,
    'science' : 95,
    'bangla' : 65
}
mark_series = pd.Series(marks, name='My Marks')
print(mark_series)

math       49
english    89
science    95
bangla     65
Name: My Marks, dtype: int64

# Scalar Value থেকে Series

In [17]:
# creating a single value series for all index
s = pd.Series(5, index=['a', 'b', 'c', 'd', 'e'])
print(s)

a    5
b    5
c    5
d    5
e    5
dtype: int64

In [18]:
pd.Series(99, index=[0,1,2,3,4,5])

0    99
1    99
2    99
3    99
4    99
5    99
dtype: int64

# Series using random and arange function

In [22]:
# Create Series using Random and Range function
s1 = np.random.random(10)  # 0 to 1
s2 = np.arange(10)
print(s1)
print(s2)
print('--'*40)
pd.Series(s1, s2)

[0.28020091 0.40109025 0.93545889 0.82209526 0.6430631  0.2523004
 0.47914256 0.10087024 0.37887419 0.582146  ]
[0 1 2 3 4 5 6 7 8 9]
--------------------------------------------------------------------------------

0    0.280201
1    0.401090
2    0.935459
3    0.822095
4    0.643063
5    0.252300
6    0.479143
7    0.100870
8    0.378874
9    0.582146
dtype: float64

# 🟢 Series এর গুরুত্বপূর্ণ Attributes
- `s.values`      🟢শুধু values array আকারে
- `s.index`       🟢index
- `s.dtype`       🟢data type
- `s.shape`       🟢shape (কতগুলো element আছে)- `

In [27]:
v = np.random.random(20)
s = pd.Series(v, index=np.arange(20))
print(s.values)
print(s.index)
print(s.dtype)
print(s.shape)
print('--'*40)
print(s)

[0.29251516 0.91220375 0.54896058 0.44789635 0.40500749 0.83524604
 0.75527568 0.30086605 0.98771029 0.26756918 0.27969551 0.3126888
 0.55160285 0.90613871 0.41439976 0.90232938 0.06490423 0.60659387
 0.60417446 0.52700917]
Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19], dtype='int64')
float64
(20,)
--------------------------------------------------------------------------------
0     0.292515
1     0.912204
2     0.548961
3     0.447896
4     0.405007
5     0.835246
6     0.755276
7     0.300866
8     0.987710
9     0.267569
10    0.279696
11    0.312689
12    0.551603
13    0.906139
14    0.414400
15    0.902329
16    0.064904
17    0.606594
18    0.604174
19    0.527009
dtype: float64

# Series Indexing

In [41]:
# Create a Series 

s1 = np.random.random(10)
s2 = np.arange(10)
s = pd.Series(s1, s2)
print(s)
print('--'*20)

# Return all elements of the series
print(s[:])

print('--'*20)
# first three elements of the Series
print(s[:3])

print('--'*20)
# Last element of the Series
print(s[-1:])

print('--'*20)
# Fetch first 4 elements in a series
print(s[:4])

print('--'*20)
# Return all elements of the series except last two elements.
print(s[:-2])

print('--'*20)
# Return all elements of the series except last element.
print(s[:-1])

print('--'*20)
# Return last two elements of the series
print(s[-2:])

0    0.250239
1    0.433408
2    0.989901
3    0.311499
4    0.274136
5    0.497756
6    0.314678
7    0.977668
8    0.116811
9    0.569855
dtype: float64
----------------------------------------
0    0.250239
1    0.433408
2    0.989901
3    0.311499
4    0.274136
5    0.497756
6    0.314678
7    0.977668
8    0.116811
9    0.569855
dtype: float64
----------------------------------------
0    0.250239
1    0.433408
2    0.989901
dtype: float64
----------------------------------------
9    0.569855
dtype: float64
----------------------------------------
0    0.250239
1    0.433408
2    0.989901
3    0.311499
dtype: float64
----------------------------------------
0    0.250239
1    0.433408
2    0.989901
3    0.311499
4    0.274136
5    0.497756
6    0.314678
7    0.977668
dtype: float64
----------------------------------------
0    0.250239
1    0.433408
2    0.989901
3    0.311499
4    0.274136
5    0.497756
6    0.314678
7    0.977668
8    0.116811
dtype: float64
----------------------------------------
8    0.116811
9    0.569855
dtype: float64

In [3]:
s = pd.Series([1,2,3,4,5,6,7,8,9,10])

# return all the elements using step 2
print(s[::2])

print('--'*20)
# revers the Series
print(s[::-1])

print('--'*20)
# Return even elements of the series
print(s[s%2==0])

print('--'*20)
# Return even index of the series
print(s[::2])

print('--'*20)
# Return odd elements of the series
print(s[::1])

print('--'*20)
# Return odd elements of the series
print(s[s%2 !=0])

print('--'*20)
# Return elements greater than 5 of the series
print(s[s > 5])

0    1
2    3
4    5
6    7
8    9
dtype: int64
----------------------------------------
9    10
8     9
7     8
6     7
5     6
4     5
3     4
2     3
1     2
0     1
dtype: int64
----------------------------------------
1     2
3     4
5     6
7     8
9    10
dtype: int64
----------------------------------------
0    1
2    3
4    5
6    7
8    9
dtype: int64
----------------------------------------
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64
----------------------------------------
0    1
2    3
4    5
6    7
8    9
dtype: int64
----------------------------------------
5     6
6     7
7     8
8     9
9    10
dtype: int64

# Concat Series

In [4]:
s1 = pd.Series([1,2,3])
s2 = s1.copy()
print(s1)
print('--'*20)
print(s2)

0    1
1    2
2    3
dtype: int64
----------------------------------------
0    1
1    2
2    3
dtype: int64

In [5]:
s3 = pd.Series([7,8,9], index=['a','b','c'])
# Append s2 and s3 Series
s4 = pd.concat([s2, s3])
print(s4)

0    1
1    2
2    3
a    7
b    8
c    9
dtype: int64

In [16]:
# Append s2 and s3 Series
# When "inplace=False" it will return a new(temporary) copy of data with the operation performed

s5 = s4.drop('a', inplace=False)  # by default inplace=False
print('After droping a:\n', s5)
print('--'*20)
print('Original s4 Series:\n', s4)

After droping a:
 0    1
1    2
2    3
b    8
c    9
dtype: int64
----------------------------------------
Original s4 Series:
 0    1
1    2
2    3
a    7
b    8
c    9
dtype: int64

In [17]:
# When we use "inplace=True" it will affect the dataframe
v = pd.Series([1,2,3,4,5,6,7], index = ['a','b','c','d','e','f','g'])
v.drop(['a','b'], inplace=True)
print(v)

c    3
d    4
e    5
f    6
g    7
dtype: int64

# Operation on Series

In [19]:
import pandas as pd
import numpy as np

v1 = pd.Series(np.array([10,20,30]))
v2 = pd.Series(np.array([1,2,3]))
print(v1)
print(v2)

0    10
1    20
2    30
dtype: int64
0    1
1    2
2    3
dtype: int64

In [20]:
# Addition of two series
print(v1.add(v2))

# Subtraction of two series
print(v1.sub(v2))
# print(s1.subtract(s2))

# Increment all numbers in a series by 9
print(v1.add(9))

0    11
1    22
2    33
dtype: int64
0     9
1    18
2    27
dtype: int64
0    19
1    29
2    39
dtype: int64

In [21]:
# Index ভিন্ন হলে
s1 = pd.Series([1,2,3], index=['a','b','c'])
s2 = pd.Series([10,20,30], index=['b','c','d'])
print(s1+s2)

a     NaN
b    12.0
c    23.0
d     NaN
dtype: float64

- এখানে শুধু `b` আর `c`' common ছিল, তাই ওইগুলোর মান যোগ হয়েছে।
- `a` আর `d` একে অপরের মধ্যে ছিল না → তাই `NaN` এসেছে।

In [23]:
# Unequal length (কোনো সমস্যা নেই)
s1 = pd.Series([1,2,3], index=['a','b','c'])
s2 = pd.Series([10,20], index=['a','c'])
print(s1-s2)
print('--'*20)
print(s1.mul(s2))

a    -9.0
b     NaN
c   -17.0
dtype: float64
----------------------------------------
a    10.0
b     NaN
c    60.0
dtype: float64

In [25]:
# Decrement all numbers in a series by 9
print(v2)
print(v2.sub(9))

0    1
1    2
2    3
dtype: int64
0   -8
1   -7
2   -6
dtype: int64

In [28]:
# Multiplication of two series
print(v1.mul(v2))
print(s1.multiply(s2))
print(s1*s2)

0    10
1    40
2    90
dtype: int64
a    10.0
b     NaN
c    60.0
dtype: float64
a    10.0
b     NaN
c    60.0
dtype: float64

In [29]:
# Multiply each element by 1000
print(v1.mul(100))

0    1000
1    2000
2    3000
dtype: int64

In [31]:
# Division
print(v1.divide(v2))
print(s1.div(s2))

0    10.0
1    10.0
2    10.0
dtype: float64
a    0.10
b     NaN
c    0.15
dtype: float64

In [41]:
# MAX number in a series
print(v)
print('max number in v: ', v.max())

# Min number in a series
print('Min number in v: ', v.min())

# Average
print('Average number in v: ', v.mean())

# Median
print('Median number in v: ', v.median())

# Standard Deviation
print('Standard Deviation number in v: ', v.std())

# describe
print(v.describe())

c    3
d    4
e    5
f    6
g    7
dtype: int64
max number in v:  7
Min number in v:  3
Average number in v:  5.0
Median number in v:  5.0
Standard Deviation number in v:  1.5811388300841898
count    5.000000
mean     5.000000
std      1.581139
min      3.000000
25%      4.000000
50%      5.000000
75%      6.000000
max      7.000000
dtype: float64

In [ ]:
# Series comparison
print(v1.equals(v2))

False
0    False
1    False
2    False
dtype: bool

In [44]:
# Can only compare identically-labeled Series objects
print(v1 == v2)

0    False
1    False
2    False
dtype: bool

In [46]:
print(s4)
s4 = s1
print(s1 == s4)

0    1
1    2
2    3
a    7
b    8
c    9
dtype: int64
a    True
b    True
c    True
dtype: bool

In [48]:
s3 = pd.Series([1,1,2,3,3,3,2,3,3,3], index=[0,1,2,3,4,5,6,7,8,9])
print(s3)
print('Count: ', s.count())

0    1
1    1
2    2
3    3
4    3
5    3
6    2
7    3
8    3
9    3
dtype: int64
Count:  10

# Series using read_csv

In [50]:
import pandas as pd
a = pd.read_csv(r'D:\Coding\all in one\Datasets\batter.csv')
a.head()

      batter  runs        avg  strike_rate
0    V Kohli  6634  36.251366   125.977972
1   S Dhawan  6244  34.882682   122.840842
2  DA Warner  5883  41.429577   136.401577
3  RG Sharma  5881  30.314433   126.964594
4   SK Raina  5536  32.374269   132.535312

In [51]:
# checking is it a dataframe or not
is_dataframe = isinstance(a, pd.DataFrame)
print(is_dataframe)

True

In [53]:
# import the dataframe as Series
batter = pd.read_csv(r'D:\Coding\all in one\Datasets\batter.csv')
batter = batter.squeeze('columns')  # DataFrame → Series
print(type(batter))
print(batter.head())

<class 'pandas.DataFrame'>
      batter  runs        avg  strike_rate
0    V Kohli  6634  36.251366   125.977972
1   S Dhawan  6244  34.882682   122.840842
2  DA Warner  5883  41.429577   136.401577
3  RG Sharma  5881  30.314433   126.964594
4   SK Raina  5536  32.374269   132.535312

In [54]:
is_dataframe = isinstance(batter, pd.DataFrame)
is_dataframe

True

# Series Methods

In [62]:
batter = pd.read_csv(r'D:\Coding\all in one\Datasets\batter.csv')
print('Head:\n', batter.head())
print('--'*40)
print('Tail:', batter.tail)
print('--'*40)
print('Custom: ', batter.head(10))
print('--'*40)
print('Randomly choose: ', batter.sample(10))
print('--'*40)
print('Value_counts: ', batter.value_counts())
print('--'*40)
# value_counts in accending order
print('Value_counts in ascending order: ', batter.value_counts(ascending=True))  
print('--'*40)
# value_counts in decending order
print('Value_counts in decending order: ', batter.value_counts(ascending=False))

Head:
       batter  runs        avg  strike_rate
0    V Kohli  6634  36.251366   125.977972
1   S Dhawan  6244  34.882682   122.840842
2  DA Warner  5883  41.429577   136.401577
3  RG Sharma  5881  30.314433   126.964594
4   SK Raina  5536  32.374269   132.535312
--------------------------------------------------------------------------------
Tail: <bound method NDFrame.tail of              batter  runs        avg  strike_rate
0           V Kohli  6634  36.251366   125.977972
1          S Dhawan  6244  34.882682   122.840842
2         DA Warner  5883  41.429577   136.401577
3         RG Sharma  5881  30.314433   126.964594
4          SK Raina  5536  32.374269   132.535312
..              ...   ...        ...          ...
600         C Nanda     0   0.000000     0.000000
601      Akash Deep     0   0.000000     0.000000
602         S Ladda     0   0.000000     0.000000
603  V Pratap Singh     0   0.000000     0.000000
604    S Lamichhane     0   0.000000     0.000000

[605 rows x 4 columns]>
--------------------------------------------------------------------------------
Custom:             batter  runs        avg  strike_rate
0         V Kohli  6634  36.251366   125.977972
1        S Dhawan  6244  34.882682   122.840842
2       DA Warner  5883  41.429577   136.401577
3       RG Sharma  5881  30.314433   126.964594
4        SK Raina  5536  32.374269   132.535312
5  AB de Villiers  5181  39.853846   148.580442
6        CH Gayle  4997  39.658730   142.121729
7        MS Dhoni  4978  39.196850   130.931089
8      RV Uthappa  4954  27.522222   126.152279
9      KD Karthik  4377  26.852761   129.267572
--------------------------------------------------------------------------------
Randomly choose:              batter  runs        avg  strike_rate
130    SA Asnodkar   423  21.150000   120.170455
2        DA Warner  5883  41.429577   136.401577
32        SE Marsh  2489  39.507937   130.109775
321     R Shepherd    58  29.000000   134.883721
560  Shoaib Akhtar     2   2.000000    25.000000
162        Y Nagar   285  20.357143   105.166052
340    AG Paunikar    49   9.800000    80.327869
270     SD Chitnis    99  14.142857   107.608696
66       KH Pandya  1326  22.100000   132.203390
180      SM Katich   241  24.100000   126.178010
--------------------------------------------------------------------------------
Value_counts:  batter          runs  avg        strike_rate
V Kohli         6634  36.251366  125.977972     1
S Dhawan        6244  34.882682  122.840842     1
DA Warner       5883  41.429577  136.401577     1
RG Sharma       5881  30.314433  126.964594     1
SK Raina        5536  32.374269  132.535312     1
                                               ..
C Nanda         0     0.000000   0.000000       1
Akash Deep      0     0.000000   0.000000       1
S Ladda         0     0.000000   0.000000       1
V Pratap Singh  0     0.000000   0.000000       1
S Lamichhane    0     0.000000   0.000000       1
Name: count, Length: 572, dtype: int64
--------------------------------------------------------------------------------
Value_counts in ascending order:  batter          runs  avg        strike_rate
V Kohli         6634  36.251366  125.977972     1
S Dhawan        6244  34.882682  122.840842     1
DA Warner       5883  41.429577  136.401577     1
RG Sharma       5881  30.314433  126.964594     1
SK Raina        5536  32.374269  132.535312     1
                                               ..
C Nanda         0     0.000000   0.000000       1
Akash Deep      0     0.000000   0.000000       1
S Ladda         0     0.000000   0.000000       1
V Pratap Singh  0     0.000000   0.000000       1
S Lamichhane    0     0.000000   0.000000       1
Name: count, Length: 572, dtype: int64
--------------------------------------------------------------------------------
Value_counts in decending order:  batter          runs  avg        strike_rate
V Kohli         6634  36.251366  125.977972     1
S Dhawan        6244  34.882682  122.840842     1
DA Warner       5883  41.429577  136.401577     1
RG Sharma       5881  30.314433  126.964594     1
SK Raina        5536  32.374269  132.535312     1
                                               ..
C Nanda         0     0.000000   0.000000       1
Akash Deep      0     0.000000   0.000000       1
S Ladda         0     0.000000   0.000000       1
V Pratap Singh  0     0.000000   0.000000       1
S Lamichhane    0     0.000000   0.000000       1
Name: count, Length: 572, dtype: int64

In [68]:
vk = pd.read_csv(r'D:\Coding\all in one\Datasets\vk.csv')
vk

     match_id  batsman_runs
0          12            62
1          17            28
2          20            64
3          27             0
4          30            10
..        ...           ...
136       624            75
137       626           113
138       632            54
139       633             0
140       636            54

[141 rows x 2 columns]

In [69]:
vk.info()

<class 'pandas.DataFrame'>
RangeIndex: 141 entries, 0 to 140
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   match_id      141 non-null    int64
 1   batsman_runs  141 non-null    int64
dtypes: int64(2)
memory usage: 2.3 KB

In [72]:
vk['batsman_runs'].sort_values()

3        0
17       0
102      0
100      0
96       0
      ...
91      99
129    100
132    108
135    109
137    113
Name: batsman_runs, Length: 141, dtype: int64