# Pandas Complete Guide

Comprehensive guide to Pandas - the most important library for data manipulation and analysis in Python.

## Table of Contents

* [Introduction](#introduction)
* [Series and DataFrames](#series-and-dataframes)
* [DataFrame Basics and Inspection](#dataframe-basics-and-inspection)
* [Reading and Writing Data](#reading-and-writing-data)
* [Data Selection and Filtering](#data-selection-and-filtering)
* [Data Cleaning](#data-cleaning)
* [Sorting and Basic Statistics](#sorting-and-basic-statistics)
* [Grouping and Aggregation](#grouping-and-aggregation)
* [Merging and Joining](#merging-and-joining)
* [Time Series Operations](#time-series-operations)
* [Advanced Tricks and Performance](#advanced-tricks-and-performance)
* [Practice Exercises

## Introduction

### What is Pandas?

Pandas is a library for data manipulation and analysis. It provides:

* **DataFrame**: 2D labeled data structure (like Excel spreadsheet)
* **Series**: 1D labeled array
* **Powerful tools**: For cleaning, transforming, and analyzing data

### Why Pandas?

* **Easy data manipulation**: Load, clean, transform data easily
* **Handles missing data**: Built-in functions for dealing with NaN
* **Time series**: Excellent support for time-based data
* **Integration**: Works seamlessly with NumPy, Matplotlib, Scikit-learn

### Installation

In [1]:
# pip install pandas

import pandas as pd
import numpy as np
print('Pandas version: ', pd.__version__)
print('Numpy version: ', np.__version__)

Pandas version:  3.0.2
Numpy version:  2.4.4

## Series and DataFrames

### Series

A Series is a one-dimensional labeled array.

In [2]:
# Creating Series
s = pd.Series([1,2,3,4,5])
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
# With custom index
s = pd.Series([10, 20, 30], index=['a','b','c'])
print(s)

a    10
b    20
c    30
dtype: int64

In [4]:
# From dictionary
s = pd.Series({
    'Alice':25,
    'Bob':30,
    'Charlie':35
})
print(s)

Alice      25
Bob        30
Charlie    35
dtype: int64

DataFrame

A DataFrame is a 2D labeled data structure with columns of potentially different types.

In [5]:
# Creating DataFrame from dictionary
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Age': [25, 30, 35, 28],
    'City': ['New York', 'London', 'Tokyo', 'Paris'],
    'Salary': [50000, 60000, 70000, 55000]
}

df = pd.DataFrame(data)
print(df)

      Name  Age      City  Salary
0    Alice   25  New York   50000
1      Bob   30    London   60000
2  Charlie   35     Tokyo   70000
3    Diana   28     Paris   55000

In [6]:
# From list of lists
data = [['Alice', 25], ['Bob', 30], ['Charlie', 35]]
df = pd.DataFrame(data, columns=['Name','Age'])
print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [7]:
# From NumPy array
arr = np.array([[1,2,3], [4,5,6]])
df = pd.DataFrame(arr, columns=['A','B','C'])
print(df)

   A  B  C
0  1  2  3
1  4  5  6

### DataFrame Properties

In [8]:

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Age': [25, 30, 35, 28],
    'City': ['New York', 'London', 'Tokyo', 'Paris'],
    'Salary': [50000, 60000, 70000, 55000]
}
df = pd.DataFrame(data)
print(df)

# print(df.shape)        # Output: (4, 4) - (rows, columns)
# print('--'*30)
# print(df.size)         # Output: 16 - total elements
# print('--'*30)
# print(df.columns)      # Output: Index(['Name', 'Age', 'City', 'Salary'])
# print('--'*30)
# print(df.index)        # Output: RangeIndex(start=0, stop=4, step=1)
# print('--'*30)
# print(df.dtypes)       # Data types of each column
# print('--'*30)
# print(df.info())       # Summary information
# print('--'*30)
# print(df.describe())   # Statistical summary

      Name  Age      City  Salary
0    Alice   25  New York   50000
1      Bob   30    London   60000
2  Charlie   35     Tokyo   70000
3    Diana   28     Paris   55000

## DataFrame Basics and Inspection

### Inspecting Data

Quickly understand your dataset using inspection functions:

In [9]:
print(df.shape)  # Output: (4, 4) - (rows, columns)

(4, 4)

In [10]:
print(df.size) # Output: 16 - total elements

16

In [11]:
print(df.columns) # Output: Index(['Name', 'Age', 'City',

Index(['Name', 'Age', 'City', 'Salary'], dtype='str')

In [12]:
print(df.index) # Output: RangeIndex(start=0, stop=4, step=1)

RangeIndex(start=0, stop=4, step=1)

In [13]:
print(df.dtypes)  # Data types of each column

Name        str
Age       int64
City        str
Salary    int64
dtype: object

In [14]:
print(df.info()) # Summary information

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Age     4 non-null      int64
 2   City    4 non-null      str
 3   Salary  4 non-null      int64
dtypes: int64(2), str(2)
memory usage: 304.0 bytes
None

In [15]:
print(df.describe())  # Statistical summary

             Age        Salary
count   4.000000      4.000000
mean   29.500000  58750.000000
std     4.203173   8539.125638
min    25.000000  50000.000000
25%    27.250000  53750.000000
50%    29.000000  57500.000000
75%    31.250000  62500.000000
max    35.000000  70000.000000

### Index & Columns Overview

Explore DataFrame components:

In [16]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Age': [25, 30, 35, 28],
    'City': ['New York', 'London', 'Tokyo', 'Paris'],
    'Salary': [50000, 60000, 70000, 55000]
}
df = pd.DataFrame(data)
print(df)

      Name  Age      City  Salary
0    Alice   25  New York   50000
1      Bob   30    London   60000
2  Charlie   35     Tokyo   70000
3    Diana   28     Paris   55000

In [17]:
# view index

print(df.index)  # Output: RangeIndex(start=0, stop=4, step=1)

RangeIndex(start=0, stop=4, step=1)

In [18]:
print(df.index.tolist())  # [0, 1, 2, 3]

[0, 1, 2, 3]

In [19]:
# View columns
print(df.columns)  # Output: Index(['Name', 'Age', 'City', 'Salary'])

Index(['Name', 'Age', 'City', 'Salary'], dtype='str')

In [20]:
# columns in list
print(df.columns.tolist)

<bound method IndexOpsMixin.tolist of Index(['Name', 'Age', 'City', 'Salary'], dtype='str')>

In [21]:
# Underlying NumPy data
print(df.values)   # Returns NumPy array

[['Alice' 25 'New York' 50000]
 ['Bob' 30 'London' 60000]
 ['Charlie' 35 'Tokyo' 70000]
 ['Diana' 28 'Paris' 55000]]

In [22]:
# Check if index/columns are unique
print(df.index.is_unique)  # True
print(df.columns.is_unique) # True

True
True

### Renaming Columns

In [23]:
# Rename single column

df = df.rename(columns = {'Age':'Years'})
print(df.columns)  # ['Name', 'Years', 'City', 'Salary']

Index(['Name', 'Years', 'City', 'Salary'], dtype='str')

In [24]:
# Rename multiple columns

df = df.rename(columns={
    'Name':'Full Name',
    'City':'Location',
    'Salary':'Income'
})
print(df.columns)

Index(['Full Name', 'Years', 'Location', 'Income'], dtype='str')

In [25]:
# Rename using mapper function
df = df.rename(columns=str.lower)  # Convert to lowercase
print(df.columns)
df = df.rename(columns=str.upper)  # Convert to uppercase
print(df.columns)

Index(['full name', 'years', 'location', 'income'], dtype='str')
Index(['FULL NAME', 'YEARS', 'LOCATION', 'INCOME'], dtype='str')

In [26]:
df

  FULL NAME  YEARS  LOCATION  INCOME
0     Alice     25  New York   50000
1       Bob     30    London   60000
2   Charlie     35     Tokyo   70000
3     Diana     28     Paris   55000

In [27]:
# In-place renaming
df.rename(columns={'YEARS':'AGE'}, inplace=True)  # affect permanently
print(df.columns)

Index(['FULL NAME', 'AGE', 'LOCATION', 'INCOME'], dtype='str')

In [28]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Age': [25, 30, 35, 28],
    'City': ['New York', 'London', 'Tokyo', 'Paris'],
    'Salary': [50000, 60000, 70000, 55000]
}
df = pd.DataFrame(data)
print(df)

      Name  Age      City  Salary
0    Alice   25  New York   50000
1      Bob   30    London   60000
2  Charlie   35     Tokyo   70000
3    Diana   28     Paris   55000

### Setting and Resetting Index

In [29]:
# Set a column as index
df_indexed = df.set_index('Name')
print(df_indexed)

         Age      City  Salary
Name
Alice     25  New York   50000
Bob       30    London   60000
Charlie   35     Tokyo   70000
Diana     28     Paris   55000

In [30]:
# Reset index (move index back to column)
df_reset = df_indexed.reset_index()
print(df_reset)

      Name  Age      City  Salary
0    Alice   25  New York   50000
1      Bob   30    London   60000
2  Charlie   35     Tokyo   70000
3    Diana   28     Paris   55000

In [31]:
# Reset index without keeping old index as column

df_reset = df_indexed.reset_index(drop=True)
print(df_reset)

   Age      City  Salary
0   25  New York   50000
1   30    London   60000
2   35     Tokyo   70000
3   28     Paris   55000

In [32]:
# Set multiple columns as index
print(df)
print('--'*30)

df_multi = df.set_index(['City', 'Name'])
print(df_multi)

      Name  Age      City  Salary
0    Alice   25  New York   50000
1      Bob   30    London   60000
2  Charlie   35     Tokyo   70000
3    Diana   28     Paris   55000
------------------------------------------------------------
                  Age  Salary
City     Name
New York Alice     25   50000
London   Bob       30   60000
Tokyo    Charlie   35   70000
Paris    Diana     28   55000

### Basic Attributes Recap
Quick reference for core attributes:

```python
# Structure
df.shape          # (rows, columns)
df.size           # Total elements
df.ndim           # Number of dimensions

# Components
df.columns        # Column names
df.index          # Row index
df.values         # NumPy array


# Data types
df.dtypes         # Data type per column
df.dtypes.value_counts()  # Count of each data type

# Memory usage
df.memory_usage()  # Memory usage per column
df.memory_usage(deep=True)  # Deep memory usage (includes objects)

## Reading and Writing Data
### Reading CSV Files

```python
# Read CSV
df = pd.read_csv('data.csv')

# with options
df = pd.read_csv('data.csv',
                 sep=',',                    # Separator
                 header=0,                   # Row to use as header
                 index_col=0,                # Column to use as index
                 na_values=['NA', 'N/A'],    # Values to treat as NaN
                 nrows=1000)                 # Read only first 1000 rows


# Read with specific columns
df = pd.read_csv('data.csv', usecols=['Name', 'Age', Salary])
print(df)

### Reading Other Formats

```python
# Excel
df = pd.read_escel(r'data.xlsx', sheet_name='Sheet1')

# JSON
df = pd.read_json(f'data.json')

# HTML tables
df = pd.read_html(f'https://example.com/table.html')[0]

# SQL
import sqlite3
conn = sqlite3.connect('database.db')
df = read_sql_query('SELECT * FROM table', conn)

### Writing Data

```python

# Write to CSV
df.to_csv('output.csv', index=False)

# Write to Excel
df.to_excel('output.xlsx', sheet_name='Data', index=False)

# Write to json
df.to_json('output.json', orient='records')

# Write to sql
df.to_sql('table_na,e',conn, if_exists='replace', index=False)

```

## Data Selection and Filtering
### Selecting Columns

In [33]:
df = pd.DataFrame(data)
df

      Name  Age      City  Salary
0    Alice   25  New York   50000
1      Bob   30    London   60000
2  Charlie   35     Tokyo   70000
3    Diana   28     Paris   55000

In [34]:
# Single column (returns Series)
ages = df['Age']
print(ages)

# Multiple columns (returns DataFrame)
subset = df[['Name', 'Age']]
print('\n',subset)

0    25
1    30
2    35
3    28
Name: Age, dtype: int64

       Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    Diana   28

### Selecting Rows

In [35]:
# By index  - iloc[]
first_row = df.iloc[0] # First row
first_three = df.iloc[:3]  # First 3 rows
print(first_row)
print('--'*30)
print(first_three)

Name         Alice
Age             25
City      New York
Salary       50000
Name: 0, dtype: object
------------------------------------------------------------
      Name  Age      City  Salary
0    Alice   25  New York   50000
1      Bob   30    London   60000
2  Charlie   35     Tokyo   70000

In [36]:
# By label - loc[]
row = df.loc[0]  # Row with index 0
print(row)

Name         Alice
Age             25
City      New York
Salary       50000
Name: 0, dtype: object

In [37]:
# First/last n rows
head = df.head(3)             # First 3 rows
tail = df.tail(3)             # Last 3 rows

print(head)
print('--'*30, tail)

      Name  Age      City  Salary
0    Alice   25  New York   50000
1      Bob   30    London   60000
2  Charlie   35     Tokyo   70000
------------------------------------------------------------       Name  Age    City  Salary
1      Bob   30  London   60000
2  Charlie   35   Tokyo   70000
3    Diana   28   Paris   55000

### Filtering

In [38]:
# Boolean indexing
young = df[df['Age']<30]
print(young)

    Name  Age      City  Salary
0  Alice   25  New York   50000
3  Diana   28     Paris   55000

In [39]:
# Multiple conditions
filtered = df[(df['Age']>25) & (df['Salary']>55000)]
print(filtered)

      Name  Age    City  Salary
1      Bob   30  London   60000
2  Charlie   35   Tokyo   70000

In [40]:
# Using query method
filtered = df.query('Age >25 and Salary >55000')
print(filtered)

      Name  Age    City  Salary
1      Bob   30  London   60000
2  Charlie   35   Tokyo   70000

In [41]:
# isin() method
cities = ['New York', 'London']
filtered = df[df['City'].isin(cities)]
print(filtered)

    Name  Age      City  Salary
0  Alice   25  New York   50000
1    Bob   30    London   60000

### iloc vs loc

In [42]:
# iloc: Integer position-based indexing
print(df.iloc[0, 1])  # Row 0, Column 1
print('--'*20)
print(df.iloc[:3, 1:3])   # Rows 0-2, Columns 1-2
print('--'*20)

# loc: Label-based indexing
print(df.loc[0, 'Age'])   # Row with index 0, column 'Age'
print('--'*20)
print(df.loc[:2, 'Name':'City'])   # Rows 0-2, columns Name to City

25
----------------------------------------
   Age      City
0   25  New York
1   30    London
2   35     Tokyo
----------------------------------------
25
----------------------------------------
      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Tokyo

## Data Cleaning

### Handling Missing Values

Detect missing entries and handle them appropriately:

**Check for missing values**
```python
print(df.isnull)   # Boolean DataFrame (True where NaN)
print(df.isna())   # Same as isnull()
print(df.isnull().sum())  # Count missing per column
print(df.isna().sum())    # same
print(df.isnull().any())  # True if any missing in column
print(df.isnull().any().any()) # True if any missing in entire Dataframe

# Drop missing values
df_clean = df.dropna()  # default axis=0. Drop rows with any NaN
df_clean = df.dropna(axis=1)  # Drop columns with any NaN
df_clean = df.dropna(subset=['Age'])  # Drop rows where Age is NaN
df_clean = df.dropna(how='all')  # Drop rows where ALL values are NaN

# Fill missing values
df_filled = df.fillna(0)  # Fill with constant (0)
df_filled = df.fillna({'Age':0, 'Salary':50000}) # Fill different columns with different values
df_filled = df.fillna(df.mean()) # Fill with mean (numeric columns only)
df_filled = df['Age'].fillna(df['Age'].mean()) # Fill specific column with its mean
df_filled = df.fillna(df.median()) # Fill with median
df_filled = df.fillna(df.mode().iloc[0])  # Fill with mode

df_ffill = df.fillna(method='ffill') # Forward fill (use previous value)
df_bfill = df.fillna(method='bfill') # Backward fill (use next value)
df_ffill_limit = df.fillna(method='ffill', limit=2) # Limit forward fill to 2 consecutive NaNs

# Interpolation
df_interp = df.interpolate() # Linear Interpolation

### Handling Duplicates

```python
# Check for duplicates
print(df.duplicated()) # Boolean Series
print(df.duplicated().sum())  # Count duplicates

# Drop duplicates
df_unique = df.drop_duplicates()# Drop all duplicates
df_unique = df.drop_duplicates(subset=['Name']) # Drop based on column

In [43]:
import pandas as pd
import numpy as np
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Age': [25, 30, 35, 28],
    'City': ['New York', 'London', 'Tokyo', 'Paris'],
    'Salary': [50000, 60000, 70000, 55000]
}
df = pd.DataFrame(data)
print(df)

      Name  Age      City  Salary
0    Alice   25  New York   50000
1      Bob   30    London   60000
2  Charlie   35     Tokyo   70000
3    Diana   28     Paris   55000

### Changing Data Types (astype)

Convert columns to correct types for data compatibility:

```python
# Check data types
print(df.dtypes)

# Convert to integer
df['Age'] = df['Age'].astype(int)
df['Age'] = df['Age'].astype('int64')

# Convert to float
df['Salary'] = df['Salary'].astype(float) 
df['Salary'] = df['Salary'].astype('float64')

# Convert to string
df['Name'] = df['Name'].astype(str)
df['Name'] = df['Name'].astype('string')

# Convert to category (saves memory for repeated values)
df['City'] = df['City'].astype('category')
print(df['City'].cat.categories)   # view categories

# Convert to datetime
df['Date'] = pd.to_datetime(df['Date'])
df['Date'] = pd.to_datetime(df['Date'], format='%Y-%m-%d')  # With format

# Convert to boolean
df['IsActive'] = df['isActive'].astype(bool)


# Convert multiple columns at once
df[['Age', 'Salary']] = df[['Age', 'Salary']].astype(float)

# Handle errors during conversion
df['Age'] = pd.to_numeric(df['Age'], errors='coerce') # Convert invalid to NaN
df['Age'] = pd.to_numeric(df['Age'], errors='ignore') # Leave invalid as-is

### Replacing Values (replace)
Clean or fix specific data points and typos:

In [44]:
df

      Name  Age      City  Salary
0    Alice   25  New York   50000
1      Bob   30    London   60000
2  Charlie   35     Tokyo   70000
3    Diana   28     Paris   55000

```python
import re

# Replace single value
df['City'] = df['City'].replace('New York', 'NYC')

# Replace multiple values
df['City'] = df['City'].replace(['New York', 'London'], ['NYC', 'LON'])

# Replacing using dictionary
df['Age'] = df.replace({'City':{
    'New Youk':'NYC',
    'London':'LON'
}})

# Replace in specific column
df['Age'] = df['Age'].replace(26, 26)

# Replace using mapping dictionary
mapping = {25:26, 30:31}
df['Age'] = df['Age'].replace(mapping)

# Replace using regex patterns
df['Name'] = df['Name'].replace(r'^A', 'Alpha', regex=True) # Replace 'A' at start
df['City'] = df['City'].replace(r'Youk$', 'city', regex=True) # Replace 'York' at end

# Replace NaN with specific value
df = df.replace(np.nan, 'Unknown')

# Replace multiple values with one
df['Status'] = df['Status'].replace(['Active', 'A', 'active'])

### Dropping Rows & Columns (drop)
Remove unnecessary rows or columns:

```python

# Drop rows by index
df_dropped = df.drop(0)  # Drop row with index 0
df_dropped = df.drop([0, 2])  # Drop rows with indices 0 and 2
df_dropped = df.drop(df.index[0:2])  # Drop first 2 rows

# Drop columns
df_dropped = df.drop('City', axis=1)  # Drop column 'City'
df_dropped = df.drop(['City', 'Age'], axis=1)
df_dropped = df.dropped(columns=['City', 'Age']) # Alternative syntax

# Drop using axis parameter
df_dropped = df.drop('City', axis=1)  # axis=1 for columns
df_dropped = df.drop(0, axis=0) # axis=0 for rows (default)

# In-place modification
df.drop('City', axis=1, inplace=True) # Modify original DataFrame

# Drop rows/columns with errors handling
df_droped = df.drop('NonExistent', axis=1, errors='ignore')  # Ignore if doesn't exist

### Detecting & Removing Duplicates

```python
# Check for duplicates
print(df.duplicated())   # Boolean Series (True for duplicates)
print(df.duplicated().sum())  # Count of duplicate rows

# Check duplicates in specific column
print(df.duplicated(subset='Name'))

# Keep parameter: 'first' (default), 'last', or False
print(df.duplicated(keep='first'))  # Mark all but first as duplicate
print(df.duplicated(keep='last'))   # Mark all but last as duplicate
print(df.duplicated(keep=False))  # Drop all duplicates

# Drop duplicates based on specific columns
df_unique = df.drop_duplicates(subset=['Name'])  # Based on Name column only
df_unique = df.duplicates(subset=['Name', 'City']) # Based on multiple columns

# in-place
df.drop_duplicates(inplace=True)

### String Operations
Use `.str` accessor for text-based filtering and cleaning:

```python

import numpy as np
import pandas as pd

# Case conversion
df['Name'].str.upper()  # Convert to uppercase
df['Name'].str.lower()  # Convert to lowercase
df['Name'].str.title()  # Convert to title case
df['Name'].str.capitalize() # Capitalize first letter

# Whitespace handling
df['Name'].str.strip( )  # Remove leading/trailing whitespace
df['Name'].str.lstrip()  # Remove leading whitespace
df['Name'].str.rstrip()  # Remove trailing whitespace

# String replacement
df['City'].str.replace(' ', '_')  # Replace spaces with underscores
df['City'].str.replace(r'[0-9]', '', regex=True)  # Remove digits using regex

# String checking (returns boolean Series for filtering)
df['Name'].str.isalpha()  # Check if all characters are alphabetic
df['City'].str.contains('o') # Check if 'o' is in the city name
df['Name'].str.contains('a/e')  # Check if 'a' or 'e' is in the name
df['Name'].str.contains('Alice|Bob')  # Check if name is 'Alice' or 'Bob'
df['Name'].str.startswith('A') # Check if name starts with 'A'
df['Name'].str.endswith('e') # Check if name ends with 'e'
df['Name'].str.match('^A.*')  # Check if matches pattern

# String splitting
df['Name'].str.split(' ') # Split by space  # Split string into list
df['Name'].str.split(' ', expand=True)  # Split into separate columns   
df = df['Name'].str.split(' ', n=1) # Split into max n parts # Split into 2 parts (first name, last name)

# String extraction
df['Name'].str.extract(r'[A-Z]') # Extract pattern
df['Name'].str.extract(r'([A-Z][a-z]+)') # Extract first capitalized word 
df['Name'].str.extract(r'([A-Z][a-z]+) ([A-Z][a-z]+)') # Extract first and last name into separate groups
df['Name'].str.findall(r'[A-Z]') # Find all occurrences of pattern (returns list) 
df['Name'].str.findall(r'[A-Z][a-z]+') # Find all capitalized words 

# String length
df['Name'].str.len() # Length of each string

# Filtering with string operations
filtered = df[df['Name'].str.contains('Alice')]  # Filter rows where name contains 'Alice'
filtered = df[df['Name'].str.startswith('A')] # Filter rows where name starts with 'A'
filtered = df[df['Name'].str.endswith('e')] # Filter rows where name ends with 'e'

## Sorting and Basic Statistics
### Sorting Data
Sort data by one or multiple columns:

```python
# Sort by single column
df_sorted = df.sort_values('Age')  # Ascending (default)
df_sorted = df.sort_values('Age', ascending=False)  # Descending    

# Sort by multiple columns
df_sorted = df.sort_values(['City', 'Age'])  # Sort by City, then Age
df_sorted = df.sort_values(['City', 'Age'], ascending=[True, False]) # City asc, Age desc # Different order for each

# Sort by index
df_sorted = df.sort_index()  # Sort by index (row labels)
df_sorted = df.sort_index(axis=1)  # Sort by column index

# In-place sorting
df.sort_values('Age', inplace=True)  # Sort by Age permanently

# Handle NaN values
df_sorted = df.sort_values('Age', na_position='first')  # NaNs at the beginning
df_sorted = df.sort_values('Age', na_position='last')   # NaNs at the end # default

### Descriptive Statistics
Summarize and understand numeric data:


```python
# Mean (average)
print(df['Age'].mean()) # Mean of Age column
print(df.mean()) # Mean of all numeric columns

# Median
print(df['Age'].median()) # Median of Age column
print(df.median()) # Median of all numeric columns

# Mode
print(df['Age'].mode()) # Mode of Age column
print(df.mode()) # Mode of each columns  

# Standard deviation
print(df['Age'].std()) # Std dev of Age column
print(df.std()) # Std dev of all numeric columns    

# Variance
print(df['Age'].var()) # Variance of Age column
print(df.var()) # Variance of all numeric columns   

# Min and Max
print(df['Age'].min()) # Minimum age
print(df['Age'].max()) # Maximum age
print(df.min()) # Minimum of each column
print(df.max()) # Maximum of each column

# Comprehensive summary
print(df.describe()) # Summary statistics for numeric columns
print(df.describe(include='all')) # Summary for all columns, including non-numeric (categorial) data

# Additional statistics
print(df['Age'].quantile(0.25)) # 25th percentile (Q1)
print(df['Age'].quantile(0.75)) # 75th percentile (Q3)
print(df['Age'].quantile([0.25, 0.5, 0.75])) # Multiple quantiles at once   
print(df['Age'].skew()) # Skewness of Age distribution
print(df['Age'].kurtosis()) # Kurtosis of Age distribution

In [49]:
import pandas as pd
import numpy as np
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Nafis', 'Mehedi', 'Evan'],
    'Age': [25, 30, 35, 28, 32, 29, 31],
    'City': ['New York', 'London', 'Tokyo', 'Paris', 'New York', 'London', 'New York'],
    'Salary': [50000, 60000, 70000, 55000, 58000, 62000, 59000]
}
df = pd.DataFrame(data)
print(df)

      Name  Age      City  Salary
0    Alice   25  New York   50000
1      Bob   30    London   60000
2  Charlie   35     Tokyo   70000
3    Diana   28     Paris   55000
4    Nafis   32  New York   58000
5   Mehedi   29    London   62000
6     Evan   31  New York   59000

### Counting Values

Find frequency or percentage of unique values:

In [50]:
# Count unique values (frequency)
print(df['City'].value_counts())

City
New York    3
London      2
Tokyo       1
Paris       1
Name: count, dtype: int64

In [48]:
# With percentages
print(df['City'].value_counts(normalize=True))

City
New York    0.25
London      0.25
Tokyo       0.25
Paris       0.25
Name: proportion, dtype: float64

In [54]:
# Sort by frequency
# print(df.value_counts('City', sort=True))
# print(df.value_counts('City', sort=False))
print(df['City'].value_counts().sort_values(ascending=True)) # Ascending order
print(df['City'].value_counts().sort_values(ascending=False)) # Descending order

City
Paris       1
Tokyo       1
London      2
New York    3
Name: count, dtype: int64
City
New York    3
London      2
Tokyo       1
Paris       1
Name: count, dtype: int64

In [55]:
# Count including NaN
print(df['City'].value_counts(dropna=False))  # Include NaN count

City
New York    3
London      2
Tokyo       1
Paris       1
Name: count, dtype: int64

In [ ]:
# Count unique values
print(df['City'].nunique())  # Number of unique values(cities)
print(df.nunique())  # Number of unique values in entire DataFrame # Unique count per column

4
Name      7
Age       7
City      4
Salary    7
dtype: int64

In [60]:
# Total count
print(df['City'].count())  # Count of non-null values in 'City' column
print(df.count())  # Count of non-null values in each column

7
Name      7
Age       7
City      7
Salary    7
dtype: int64

### Correlation & Covariance
Understand relationships between numerical columns:

In [ ]:
# Correlation matrix
print(df[['Age', 'Salary']].corr()) # Correlation between Age and Salary

             Age    Salary
Age     1.000000  0.878981
Salary  0.878981  1.000000

In [66]:
# Correlation with specific method
print(df[['Age', 'Salary']].corr(method='pearson'))  # Pearson correlation(default)
print(df[['Age', 'Salary']].corr(method='spearman'))  # Spearman correlation
# print(df[['Age', 'Salary']].corr(method='kendall'))  # Kendall correlation

             Age    Salary
Age     1.000000  0.878981
Salary  0.878981  1.000000
             Age    Salary
Age     1.000000  0.642857
Salary  0.642857  1.000000

In [67]:
# Correlation with single column
print(df['Age'].corr(df['Salary']))  # Correlation between Age and Salary

0.8789807493452386

In [ ]:
# Covariance matrix
print(df[['Age', 'Salary']].cov())  # Covariance between Age and Salary

                 Age        Salary
Age        10.000000  1.716667e+04
Salary  17166.666667  3.814286e+07
17166.666666666664

In [ ]:
print(df['Age'].cov(df['Salary']))  # Covariance between Age and Salary

17166.666666666664